import streamlit as st
import matplotlib.pyplot as plt
import numpy as np
import re
import sys
import os
import random
import requests
import json
from datetime import datetime
from dotenv import load_dotenv

# ReportLab imports for PDF Generation
from reportlab.lib.pagesizes import letter, landscape
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import io

# .env ֆայլի բեռնում
load_dotenv()

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
API_URL = "https://openrouter.ai/api/v1/chat/completions"

# Root directory path alignment
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# --- PAGE CONFIG & CUSTOM STYLING ---
logo_path = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "image_cde603.png"
)

if os.path.exists(logo_path):
    st.set_page_config(
        page_title="Հենք Հիմնադրամ - AI Mock Interview Platform",
        page_icon=logo_path,
        layout="wide"
    )
else:
    st.set_page_config(
        page_title="Հենք Հիմնադրամ - AI Mock Interview Platform",
        page_icon="🌟",
        layout="wide"
    )

# --- GLOBAL STYLING (CSS) ---
st.markdown("""
<style>
    .stApp {
        background-color: #F8FAFC;
        font-family: 'Inter', sans-serif;
    }
    .hero-card {
        background: linear-gradient(135deg, #FFFFFF 0%, #F1F5F9 100%);
        border: 1px solid #E2E8F0;
        border-radius: 20px;
        padding: 2.5rem;
        box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.05);
        margin-bottom: 2rem;
    }
    .congrats-card {
        background: linear-gradient(135deg, #ECFDF5 0%, #D1FAE5 100%);
        border: 2px solid #10B981;
        border-radius: 20px;
        padding: 2.5rem;
        text-align: center;
        box-shadow: 0 10px 25px -5px rgba(16, 185, 129, 0.1);
    }
    .encourage-card {
        background: linear-gradient(135deg, #FFFBEB 0%, #FEF3C7 100%);
        border: 2px solid #F59E0B;
        border-radius: 20px;
        padding: 2.5rem;
        text-align: center;
        box-shadow: 0 10px 25px -5px rgba(245, 158, 11, 0.1);
    }
    .cheating-alert {
        background: linear-gradient(135deg, #FEF2F2 0%, #FEE2E2 100%);
        border: 2px solid #EF4444;
        border-radius: 15px;
        padding: 1.5rem;
        text-align: center;
        color: #991B1B;
        font-weight: 700;
        margin-bottom: 1.5rem;
    }
    .stButton>button {
        border-radius: 12px;
        font-weight: 600;
        padding: 0.6rem 1.5rem;
        transition: all 0.3s ease;
    }
    .stButton>button:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 12px rgba(37, 99, 235, 0.2);
    }
</style>
""", unsafe_allow_html=True)


# --- OPENROUTER & GEMINI INTEGRATION ---
def call_openrouter_api(messages):
    if not OPENROUTER_API_KEY:
        return None

    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "http://localhost:8501",
        "X-Title": "AI Mock Interview Platform"
    }

    payload = {
        "model": "google/gemini-1.5-flash",
        "messages": messages,
        "temperature": 0.95
    }

    try:
        response = requests.post(API_URL, headers=headers, json=payload, timeout=30)
        if response.status_code == 200:
            res_json = response.json()
            return res_json['choices'][0]['message']['content']
        else:
            return None
    except Exception:
        return None


def detect_ai_usage_and_evaluate(question, answer, difficulty):
    """Խիստ ստուգում AI-ի կողմից գեներացված կամ արտաքին աղբյուրից պատճենված պատասխանների համար"""
    ans_clean = answer.strip()
    if not ans_clean or len(ans_clean.split()) < 2:
        return 0, "Պատասխանը բացակայում է կամ չափազանց կարճ է (0/100)։", False

    ai_indicators = [
        "որպես արհեստական բանականություն", "պես ai", "հետևյալ կերպ", "եզրափակելով",
        "summarize", "as an ai", "հաշվի առնելով", "առաջին հերթին պետք է նշել",
        "կարևոր է ընդգծել", "ամփոփելով կարող ենք ասել"
    ]

    local_ai_detected = any(ind in ans_clean.lower() for ind in ai_indicators) or len(ans_clean.split()) > 120

    if OPENROUTER_API_KEY:
        prompt = f"""You are a strict, uncompromising anti-cheating AI detector for technical interviews.
Analyze the candidate's answer to determine if it was generated by an AI assistant or copied from an external source rather than written on the spot by a human.

Question: {question}
Candidate's Answer: {answer}

Strict Rules:
1. If the answer sounds too polished, structured like an LLM response, uses formal lists/markdown blocks typical of ChatGPT, or seems AI-assisted, set IS_AI to TRUE.
2. If it is detected as AI, set SCORE to 0 and provide a strict warning in Armenian.
3. Be strict. If there's a high probability of AI usage, flag it as TRUE.

Format your response EXACTLY like this:
IS_AI: [TRUE or FALSE]
SCORE: [0 if TRUE, otherwise 0-100]
FEEDBACK: [Detailed feedback or cheating warning in Armenian]"""

        messages = [{"role": "user", "content": prompt}]
        response = call_openrouter_api(messages)

        if response:
            try:
                is_ai = local_ai_detected
                score = 50
                feedback = "Պատասխանը ընդունված է:"
                lines = response.split('\n')
                for line in lines:
                    if line.startswith("IS_AI:"):
                        is_ai_str = line.replace("IS_AI:", "").strip().upper()
                        if "TRUE" in is_ai_str:
                            is_ai = True
                    elif line.startswith("SCORE:"):
                        score_str = line.replace("SCORE:", "").strip().replace("%", "")
                        score = int(''.join(filter(str.isdigit, score_str)))
                    elif line.startswith("FEEDBACK:"):
                        feedback = line.replace("FEEDBACK:", "").strip()

                if is_ai:
                    return 0, "⚠️ Հայտնաբերվել է արհեստական բանականության (AI) օգտագործում։ Պատասխանը հաշվի չի առնվում և գնահատվում է 0 միավոր։", True

                return min(max(score, 0), 100), feedback, False
            except Exception:
                pass

    if local_ai_detected:
        return 0, "⚠️ Հայտնաբերվել է արհեստական բանականության (AI) օգտագործում։ Պատասխանը հաշվի չի առնվում (0/100)։", True

    word_count = len(ans_clean.split())
    fallback_score = min(max(word_count * 3, 35), 90)
    return fallback_score, "Պատասխանը հաջողությամբ գրանցվեց և վերլուծվեց։", False


def get_next_question(topic, level, difficulty, used_questions):
    if OPENROUTER_API_KEY:
        used_str = "\n".join([f"- {q}" for q in used_questions]) if used_questions else "None"

        prompt = f"""You are a strict technical interviewer for a {level} position in {topic}.
Generate ONE completely unique, fresh, creative and distinct technical interview question suitable for difficulty level: {difficulty}.

CRITICAL RULES:
1. The question MUST be strictly written in Armenian (հայերեն).
2. DO NOT repeat, rephrase, or use any concepts from these previous questions in this session:
{used_str}

Return ONLY the text of the question, without any introductory phrases, prefixes, or quotes."""

        messages = [{"role": "user", "content": prompt}]

        for _ in range(2):
            question = call_openrouter_api(messages)
            if question:
                q_clean = question.strip()
                if q_clean and q_clean not in used_questions:
                    return q_clean

    fallback_pool = {
        "Python Core & Data Structures": [
            "Ի՞նչ տարբերություն կա List-ի և Tuple-ի միջև, և ե՞րբ պետք է օգտագործել դրանցից յուրաքանչյուրը:",
            "Բացատրեք Python-ում Decorator-ների աշխատանքի սկզբունքը և բերեք գործնական օրինակ:",
            "Ինչպե՞ս է աշխատում Garbage Collector-ը Python-ում (Reference counting և Generational GC):"
        ],
        "FastAPI & REST API Architecture": [
            "Ի՞նչ է Dependency Injection-ը և ի՞նչ խնդիրներ է այն լուծում FastAPI-ում:",
            "Ինչպե՞ս է կազմակերպվում ասինխրոն (async/await) աշխատանքը FastAPI-ում:",
            "Ինչպե՞ս է աշխատում Pydantic-ը տվյալների վավերացման (validation) գործընթացում:"
        ],
        "Database, SQL & ORM": [
            "Բացատրեք N+1 հարցումների (queries) խնդիրը և նշեք դրա լուծման տարբերակները ORM-ում:",
            "Ո՞րն է տարբերությունը INNER JOIN-ի և LEFT JOIN-ի միջև, բերեք SQL օրինակ:",
            "Ի՞նչ են ինդեքսները (Indexes) տվյալների բազաներում, ինչպե՞ս են դրանք ազդում կատարողականի վրա:"
        ],
        "System Design & Asyncio": [
            "Ինչպե՞ս է աշխատում Python-ի Asyncio-ի Event Loop-ը և որո՞նք են դրա սահմանափակումները:",
            "Ի՞նչ է Microservices արխիտեկտուրան և որո՞նք են դրա առավելություններն ու թերությունները Monolith-ի համեմատ:",
            "Ինչպե՞ս կնախագծեիք URL Shortener համակարգ (System Design հիմնական մոտեցումները):"
        ]
    }

    topic_list = fallback_pool.get(topic, [f"Մասնագիտական հարց {topic}-ի վերաբերյալ:"])
    available_questions = [q for q in topic_list if q not in used_questions]

    if available_questions:
        return random.choice(available_questions)
    else:
        return f"({topic}) Խորացված տեխնիկական վերլուծություն #{len(used_questions) + 1} ({difficulty}): Որո՞նք են ձեր կիրառած լավագույն պրակտիկաները այս բաժնում:"


def is_valid_name(name_str):
    pattern = r'^[a-zA-Zа-яА-Яա-ֆԱ-Ֆ-]+\s*$'
    return bool(re.match(pattern, name_str.strip()))


def save_feedback_to_separate_storage(feedback_data):
    storage_file = "henk_feedback_log.json"
    data_list = []

    if os.path.exists(storage_file):
        try:
            with open(storage_file, "r", encoding="utf-8") as f:
                data_list = json.load(f)
        except Exception:
            data_list = []

    data_list.append(feedback_data)

    try:
        with open(storage_file, "w", encoding="utf-8") as f:
            json.dump(data_list, f, ensure_ascii=False, indent=4)
        return True
    except Exception:
        return False


# --- PDF CERTIFICATE GENERATOR FUNCTION ---
def generate_certificate_pdf(full_name, topic, score):
    buffer = io.BytesIO()
    # Landscape A4 size
    c = canvas.Canvas(buffer, pagesize=landscape(letter))
    width, height = landscape(letter)

    # Background frame / Border
    c.setStrokeColor(colors.HexColor("#2563EB"))
    c.setLineWidth(4)
    c.rect(30, 30, width - 60, height - 60, stroke=1, fill=0)

    c.setStrokeColor(colors.HexColor("#93C5FD"))
    c.setLineWidth(1)
    c.rect(38, 38, width - 76, height - 76, stroke=1, fill=0)

    # Header / Organization
    c.setFillColor(colors.HexColor("#0F172A"))
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width / 2, height - 90, "ՀԵՆՔ ՀԻՄՆԱԴՐԱՄ")

    c.setFont("Helvetica", 14)
    c.setFillColor(colors.HexColor("#64748B"))
    c.drawCentredString(width / 2, height - 120, "AI Mock Interview Platform — Հավաստագիր")

    # Certificate Title
    c.setFont("Helvetica-Bold", 32)
    c.setFillColor(colors.HexColor("#2563EB"))
    c.drawCentredString(width / 2, height - 175, "ՀԱՎԱՍՏԱԳԻՐ")

    c.setFont("Helvetica", 13)
    c.setFillColor(colors.HexColor("#334155"))
    c.drawCentredString(width / 2, height - 210, "Սույն հավաստագիրը տրվում է հաստատելու, որ")

    # Candidate Name
    c.setFont("Helvetica-Bold", 26)
    c.setFillColor(colors.HexColor("#0F172A"))
    c.drawCentredString(width / 2, height - 255, full_name)

    # Details
    c.setFont("Helvetica", 13)
    c.setFillColor(colors.HexColor("#334155"))
    c.drawCentredString(
        width / 2,
        height - 300,
        f"հաջողությամբ անցել է մասնագիտական հարցազրույցը «{topic}» ուղղությամբ"
    )
    c.drawCentredString(
        width / 2,
        height - 325,
        f"և ցուցաբերել է բարձր արդյունք՝ {score:.1f}% ընդհանուր գնահատականով։"
    )

    # Date and Signature line
    date_str = datetime.now().strftime("%d.%m.%Y")
    c.setFont("Helvetica", 11)
    c.setFillColor(colors.HexColor("#64748B"))
    c.drawString(80, 75, f"Ամսաթիվ՝ {date_str}")

    c.drawRightString(width - 80, 75, "Հենք Հիմնադրամի Ղեկավարություն")
    c.setStrokeColor(colors.HexColor("#CBD5E1"))
    c.setLineWidth(1)
    c.line(width - 250, 95, width - 80, 95)

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer


# --- STATE MANAGEMENT ---
if "step" not in st.session_state:
    st.session_state.step = "welcome"
if "q_index" not in st.session_state:
    st.session_state.q_index = 0
if "user_profile" not in st.session_state:
    st.session_state.user_profile = {}
if "selected_topic" not in st.session_state:
    st.session_state.selected_topic = ""
if "selected_level" not in st.session_state:
    st.session_state.selected_level = "Mid-level"
if "current_difficulty" not in st.session_state:
    st.session_state.current_difficulty = "Medium"
if "history" not in st.session_state:
    st.session_state.history = []
if "used_questions" not in st.session_state:
    st.session_state.used_questions = []
if "current_q_text" not in st.session_state:
    st.session_state.current_q_text = ""

# ---------------------------------------------------------
# ԷՋ 1: WELCOME PAGE
# ---------------------------------------------------------
if st.session_state.step == "welcome":

    col_l, col_r = st.columns([1, 10])
    with col_l:
        if os.path.exists(logo_path):
            st.image(logo_path, width=70)
        else:
            st.write("🌟")
    with col_r:
        st.markdown("<h3 style='color: #2563EB; margin: 0; padding-top: 10px;'>Հենք Հիմնադրամ</h3>",
                    unsafe_allow_html=True)

    st.markdown("""
        <h1 style="font-size: 2.8rem; font-weight: 800; color: #0F172A; margin-top: 1rem; margin-bottom: 0.5rem;">
            Բարի գալուստ <span style="color: #2563EB;">AI Մասնագիտական Հարթակ</span>
        </h1>
        <p style="font-size: 1.2rem; color: #64748B; margin-bottom: 2rem;">
            Որտեղ արժեքները, նորարարությունն ու մարդկային ներուժը միավորվում են՝ կերտելու մեր վաղվա ամուր հիմքերը։ <a href="http://localhost:8501/url?id=2" target="_blank" style="color: #2563EB; text-decoration: none; font-weight: 600;">🌐 Այցելել պաշտոնական կայք</a>
        </p>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div class="hero-card">
        <h3 style="color: #1E293B; margin-top: 0; font-weight: 700;">✨ Մեր մասին</h3>
        <p style="color: #334155; font-size: 1.05rem; line-height: 1.7; margin-bottom: 1rem;">
            <b>«Հենք» հիմնադրամը</b> ավելին է, քան պարզապես կազմակերպություն։ Սա միասնական և ջերմ ընտանիք է, որտեղ յուրաքանչյուր անհատի ձայնը լսելի է, իսկ գաղափարները՝ արժևորված։ Մենք հավատում ենք, որ մեր հաջողության գրավականը նպատակասլաց, ստեղծարար և զարգանալ ձգտող մասնագետներն են։
        </p>
        <p style="color: #334155; font-size: 1.05rem; line-height: 1.7; margin: 0;">
            Լրացրեք ձեր տվյալները ստորև և անցեք արհեստական բանականությամբ ուղղորդվող հարցազրույցը։
        </p>
    </div>
    """, unsafe_allow_html=True)

    with st.form("welcome_form"):
        st.markdown("### 📝 Անձնական Տվյալներ")
        col1, col2, col3 = st.columns([2, 2, 1])
        with col1:
            first_name = st.text_input("Անուն *", value="", placeholder="Օրինակ՝ Կարեն")
        with col2:
            last_name = st.text_input("Ազգանուն *", value="", placeholder="Օրինակ՝ Նավասարդյան")
        with col3:
            age = st.number_input("Տարիք", min_value=16, max_value=80, value=25)

        st.markdown("---")
        st.markdown("### 🎯 Հարցազրույցի Պարամետրեր")

        col_topic, col_level = st.columns(2)
        with col_topic:
            topic = st.selectbox(
                "Մասնագիտական Թեմա",
                [
                    "Python Core & Data Structures",
                    "FastAPI & REST API Architecture",
                    "Database, SQL & ORM",
                    "System Design & Asyncio"
                ]
            )
        with col_level:
            user_level = st.selectbox(
                "Ձեր Մասնագիտական Մակարդակը (Level)",
                [
                    "Junior (0-1 տարի)",
                    "Mid-level (2-4 տարի)",
                    "Senior (5+ տարի)",
                    "Lead / System Architect"
                ]
            )

        st.write("")
        submit_welcome = st.form_submit_button("Սկսել Հարցազրույցը 🚀", use_container_width=True)

    if submit_welcome:
        if not first_name.strip() or not last_name.strip():
            st.error("Խնդրում ենք լրացնել անունը և ազգանունը սկսելու համար։")
        elif not is_valid_name(first_name) or not is_valid_name(last_name):
            st.error("⚠️ Անունն ու ազգանունը կարող են պարունակել միայն տառեր և «-» նշանը։")
        else:
            initial_diff = "Easy" if "Junior" in user_level else (
                "Hard" if "Senior" in user_level or "Lead" in user_level else "Medium")
            st.session_state.user_profile = {"first_name": first_name.strip(), "last_name": last_name.strip(),
                                             "age": age}
            st.session_state.selected_topic = topic
            st.session_state.selected_level = user_level
            st.session_state.current_difficulty = initial_diff
            st.session_state.step = "interview"
            st.session_state.q_index = 0
            st.session_state.history = []
            st.session_state.used_questions = []
            st.session_state.current_q_text = ""
            st.rerun()

# ---------------------------------------------------------
# ԷՋ 2: INTERVIEW PAGE
# ---------------------------------------------------------
elif st.session_state.step == "interview":
    idx = st.session_state.q_index
    total_q = 4
    topic = st.session_state.selected_topic
    level = st.session_state.selected_level
    difficulty = st.session_state.current_difficulty

    if not st.session_state.current_q_text:
        with st.spinner("🤖 Գեներացվում է նոր, չկրկնվող հարց..."):
            q_generated = get_next_question(topic, level, difficulty, st.session_state.used_questions)
            st.session_state.current_q_text = q_generated
            st.session_state.used_questions.append(q_generated)

    st.title(f"❓ Հարց {idx + 1} / {total_q}")
    st.caption(f"Թեմա՝ **{topic}** | Մակարդակ՝ **{level}** | Ընթացիկ բարդություն՝ **{difficulty}**")
    st.progress((idx + 1) / total_q)
    st.divider()

    st.markdown(f"### 💬 {st.session_state.current_q_text}")

    user_ans = st.text_area(
        "Ձեր պատասխանը․",
        value="",
        placeholder="Գրեք Ձեր պատասխանն այստեղ մանրամասն...",
        height=160,
        key=f"ans_input_{idx}"
    )

    btn_label = "Հաջորդ Հարցը ➡️" if idx + 1 < total_q else "Ավարտել և Դիտել Վերլուծությունը 📊"
    if st.button(btn_label, use_container_width=True):
        with st.spinner("🤖 Ստուգվում է պատասխանը և ԱԲ-ի (AI) առկայությունը..."):
            score, feedback, is_ai_detected = detect_ai_usage_and_evaluate(st.session_state.current_q_text, user_ans,
                                                                           difficulty)

        if is_ai_detected:
            st.markdown("""
            <div class="cheating-alert">
                ⚠️ Հայտնաբերվեց արհեստական բանականության (AI) օգտագործում։ Այս պատասխանը հաշվի չի առնվում և գնահատվում է 0 միավոր։
            </div>
            """, unsafe_allow_html=True)

        if score >= 75:
            next_diff = "Hard"
        elif score >= 40:
            next_diff = "Medium"
        else:
            next_diff = "Easy"

        st.session_state.history.append({
            "q_num": f"Q{idx + 1}",
            "question": st.session_state.current_q_text,
            "answer": user_ans,
            "difficulty": difficulty,
            "score": score,
            "feedback": feedback,
            "is_ai": is_ai_detected,
            "word_count": len(user_ans.strip().split())
        })

        st.session_state.current_q_text = ""

        if idx + 1 < total_q:
            st.session_state.q_index += 1
            st.session_state.current_difficulty = next_diff
            st.rerun()
        else:
            st.session_state.step = "analytics"
            st.rerun()

# ---------------------------------------------------------
# ԷՋ 3: ANALYTICS
# ---------------------------------------------------------
elif st.session_state.step == "analytics":
    user = st.session_state.user_profile
    history = st.session_state.history

    st.title("📊 Հարցազրույցի Ամփոփում և Վերլուծություն")
    st.success(
        f"Շնորհակալություն, **{user.get('first_name')} {user.get('last_name')}**։ Ձեր հարցազրույցն հաջողությամբ ավարտվեց։")
    st.divider()

    st.subheader("📝 Ձեր Պատասխանները և Գնահատականները")
    for item in history:
        badge = " ❌ [ԱԲ հայտնաբերված է - 0 միավոր]" if item.get('is_ai') else ""
        with st.expander(
                f"📌 {item['q_num']}: {item['question']} (Բարդություն՝ {item['difficulty']}) - `{item['score']}/100`{badge}"):
            st.write(f"**Պատասխան:** {item['answer'] if item['answer'].strip() else '_[Պատասխան չի տրվել]_'}")
            st.write(f"**AI Կարծիք:** {item['feedback']}")

    st.divider()
    st.subheader("📈 Վերլուծական Գրաֆիկներ")

    labels = [h['q_num'] for h in history]
    scores = [h['score'] for h in history]
    word_counts = [h['word_count'] for h in history]
    difficulties = [h['difficulty'] for h in history]

    fig, axs = plt.subplots(2, 2, figsize=(12, 8), dpi=100)
    fig.patch.set_facecolor('#F8FAFC')

    # Chart 1
    axs[0, 0].plot(labels, scores, marker='o', markersize=8, color='#2563EB', linewidth=3, label="Միավոր")
    axs[0, 0].axhline(y=75, color='#EF4444', linestyle='--', alpha=0.7, label="Passing (75%)")
    axs[0, 0].set_title("1. Առաջադիմության Դինամիկան", fontsize=11, fontweight='bold')
    axs[0, 0].set_ylim(-5, 105)
    axs[0, 0].grid(True, linestyle=':', alpha=0.6)
    axs[0, 0].legend(loc="upper left")

    # Chart 2
    diff_colors = {"Easy": "#10B981", "Medium": "#F59E0B", "Hard": "#EF4444"}
    colors = [diff_colors.get(d, "#3B82F6") for d in difficulties]
    axs[0, 1].bar(labels, scores, color=colors, width=0.5, edgecolor='#1E293B', linewidth=0.8)
    axs[0, 1].set_title("2. Միավորներն ըստ Բարդության", fontsize=11, fontweight='bold')
    axs[0, 1].set_ylim(-5, 105)
    axs[0, 1].grid(axis='y', linestyle=':', alpha=0.6)

    # Chart 3
    axs[1, 0].scatter(word_counts, scores, color='#8B5CF6', s=120, edgecolors='#4C1D95', zorder=5)
    axs[1, 0].set_title("3. Ծավալի (Բառեր) և Միավորի Կապը", fontsize=11, fontweight='bold')
    axs[1, 0].set_xlabel("Բառերի Քանակ", fontsize=9)
    axs[1, 0].set_ylabel("Միավոր", fontsize=9)
    axs[1, 0].set_ylim(-5, 105)
    axs[1, 0].grid(True, linestyle=':', alpha=0.6)

    # Chart 4
    high = sum(1 for s in scores if s >= 75)
    mid = sum(1 for s in scores if 40 <= s < 75)
    low = sum(1 for s in scores if s < 40)
    pie_data = [high, mid, low]
    pie_labels = ['Բարձր (75+)', 'Միջին (40-74)', 'Ցածր (<40)']
    pie_colors = ['#10B981', '#F59E0B', '#EF4444']

    non_zero = [(d, l, c) for d, l, c in zip(pie_data, pie_labels, pie_colors) if d > 0]
    if non_zero:
        d_vals, d_labs, d_cols = zip(*non_zero)
        axs[1, 1].pie(d_vals, labels=d_labs, colors=d_cols, autopct='%1.1f%%', startangle=140)
    axs[1, 1].set_title("4. Որակի Բաշխում", fontsize=11, fontweight='bold')

    plt.tight_layout(pad=2.0)
    st.pyplot(fig)

    st.write("")
    if st.button("Անցնել Դիմում-Բողոք-Առաջարկների Բաժին 📝", use_container_width=True):
        st.session_state.step = "feedback_page"
        st.rerun()

# ---------------------------------------------------------
# ԷՋ 4: ԴԻՄՈՒՄ, ԲՈՂՈՔ, ԱՌԱՋԱՐԿՆԵՐԻ ԲԱԺԻՆ
# ---------------------------------------------------------
elif st.session_state.step == "feedback_page":
    user = st.session_state.user_profile
    st.title("📋 Դիմում, Բողոք և Առաջարկներ")
    st.markdown("""
    <p style="color: #475569; font-size: 1.05rem;">
        Ձեր կարծիքը, առաջարկները կամ բողոքները շատ կարևոր են մեզ համար։ Այս տվյալներն առանձնացված են և պահպանվելու են առանձին բազայում՝ հետագա բարելավումների համար։
    </p>
    """, unsafe_allow_html=True)
    st.divider()

    with st.form("feedback_form"):
        feedback_type = st.selectbox(
            "Ընտրեք դիմումի տեսակը",
            ["Առաջարկ (Suggestion)", "Բողոք (Complaint)", "Դիմում / Ընդհանուր կարծիք (Application/Feedback)"]
        )
        subject = st.text_input("Վերնագիր / Հարցի համառոտ նկարագրություն *",
                                placeholder="Օրինակ՝ Հարթակի վերաբերյալ առաջարկ...")
        details = st.text_area(
            "Մանրամասն նկարագրություն կամ առաջարկ *",
            placeholder="Գրեք ձեր մանրամասն մեկնաբանությունները այստեղ...",
            height=150
        )
        submit_feedback = st.form_submit_button("Ուղարկել և Պահպանել 📥", use_container_width=True)

    if submit_feedback:
        if not subject.strip() or not details.strip():
            st.error("Խնդրում ենք լրացնել վերնագիրը և մանրամասն նկարագրությունը։")
        else:
            payload_data = {
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "user": f"{user.get('first_name', '')} {user.get('last_name', '')}",
                "age": user.get('age', 0),
                "topic": st.session_state.selected_topic,
                "level": st.session_state.selected_level,
                "type": feedback_type,
                "subject": subject.strip(),
                "details": details.strip()
            }

            success = save_feedback_to_separate_storage(payload_data)
            if success:
                st.success("✅ Ձեր դիմում/առաջարկը հաջողությամբ պահպանվեց առանձին բազայում (henk_feedback_log.json)։")
            else:
                st.error("⚠️ Տվյալների պահպանման ժամանակ առաջացավ խնդիր։")

    st.write("")
    if st.button("Դիտել Վերջնական Արդյունքը 🏆", use_container_width=True):
        st.session_state.step = "final_result"
        st.rerun()

# ---------------------------------------------------------
# ԷՋ 5: ՎԵՐՋՆԱԿԱՆ ԱՐԴՅՈՒՆՔԻ ԷՋ (ԿԵՆՏՐՈՆԱՑՎԱԾ)
# ---------------------------------------------------------
elif st.session_state.step == "final_result":
    user = st.session_state.user_profile
    history = st.session_state.history

    scores = [h['score'] for h in history]
    avg_score = sum(scores) / len(scores) if scores else 0
    ai_violation_count = sum(1 for h in history if h.get('is_ai'))

    st.markdown("<h1 style='text-align: center;'>🏆 Վերջնական Արդյունք</h1>", unsafe_allow_html=True)
    st.write("")

    if ai_violation_count > 0:
        st.markdown(f"""
        <div class="encourage-card">
            <h1 style="color: #92400E; margin-bottom: 0.5rem; text-align: center;">⚠️ Հարցազրույցն Ավարտված է Խախտումով</h1>
            <h3 style="color: #B45309; text-align: center;">Հարգելի {user.get('first_name')} {user.get('last_name')}։</h3>
            <p style="font-size: 1.1rem; color: #78350F; margin-top: 1rem; text-align: center;">
                Հարցազրույցի ընթացքում հայտնաբերվել է արհեստական բանականության (AI) օգտագործում (<b>{ai_violation_count}</b> դեպք)։<br>
                Համաձայն կանոնների՝ այդ պատասխանները չեն հաշվվել (ստացել են 0 միավոր)։
            </p>
        </div>
        """, unsafe_allow_html=True)
    elif avg_score >= 75:
        st.balloons()
        st.markdown(f"""
        <div class="congrats-card">
            <h1 style="color: #065F46; margin-bottom: 0.5rem; text-align: center;">🎉 Շնորհավորում ենք, {user.get('first_name')} {user.get('last_name')}։</h1>
            <h3 style="color: #047857; text-align: center;">Դուք հաջողությամբ անցաք Արհեստական Բանականության (AI) փուլը։</h3>
            <p style="font-size: 1.1rem; color: #064E3B; margin-top: 1rem; text-align: center;">
                Ձեր միջին արդյունքն է՝ <b>{avg_score:.1f}%</b> (Պահանջվող շեմը՝ 75%)։<br>
                Դուք ցուցաբերեցիք բարձր մասնագիտական գիտելիքներ <b>{st.session_state.selected_topic}</b> թեմայով։
            </p>
        </div>
        """, unsafe_allow_html=True)

        # --- PDF CERTIFICATE DOWNLOAD BUTTON ---
        st.write("")
        full_name_str = f"{user.get('first_name')} {user.get('last_name')}"
        pdf_buffer = generate_certificate_pdf(full_name_str, st.session_state.selected_topic, avg_score)

        col_c1, col_c2, col_c3 = st.columns([1, 2, 1])
        with col_c2:
            st.download_button(
                label="📥 Ներբեռնել Հավաստագիրը (PDF)",
                data=pdf_buffer,
                file_name=f"Henk_Certificate_{user.get('first_name')}.pdf",
                mime="application/pdf",
                use_container_width=True
            )
    else:
        st.markdown(f"""
        <div class="encourage-card">
            <h1 style="color: #92400E; margin-bottom: 0.5rem; text-align: center;">💪 Լավ փորձ էր, {user.get('first_name')} {user.get('last_name')}։</h1>
            <h3 style="color: #B45309; text-align: center;">Սա հիանալի քայլ էր Ձեր գիտելիքները ստուգելու համար։</h3>
            <p style="font-size: 1.1rem; color: #78350F; margin-top: 1rem; text-align: center;">
                Ձեր միջին արդյունքն է՝ <b>{avg_score:.1f}%</b> (Անցողիկ շեմը՝ 75%)։<br>
                Խորհուրդ ենք տալիս ևս մեկ անգամ կրկնել թեման և փորձել նորից։
            </p>
        </div>
        """, unsafe_allow_html=True)

    st.write("")
    st.write("")

    if st.button("🔄 Սկսել Նոր Հարցազրույց", use_container_width=True):
        st.session_state.step = "welcome"
        st.session_state.q_index = 0
        st.session_state.history = []
        st.session_state.used_questions = []
        st.session_state.current_q_text = ""
        st.rerun()